FRC1740/CommandBased_2023

src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/commands/TurnToAngle.java, src/main/java/frc/robot/commands/TurnToAngleProfiled.java, src/main/java/frc/robot/subsystems/DriveSubsystem.java
this fixed inputs from x and y axis for rotation, also squared driving
=> Axis fix and square driving

src/main/java/frc/robot/subsystems/SignalLEDs.java
Reverts FRC1740/CommandBased_2023#25 - Ronan's commits broke everything...
=> Revert "SignalLEDs now work on co-driver A/B buttons"

src/main/java/frc/robot/subsystems/SignalLEDs.java
Reverts FRC1740/CommandBased_2023#27
=> Revert "Revert "SignalLEDs now work on co-driver A/B buttons""

src/main/java/frc/constants/ArmConstants.java, src/main/java/frc/constants/DriveConstants.java, src/main/java/frc/robot/subsystems/Arm.java, src/main/java/frc/robot/subsystems/Claw.java
=> Refined gear ratios from build team. Cleanup excessive FIXME

.SysId/sysid.json, src/main/java/frc/constants/ArmConstants.java, src/main/java/frc/constants/ClawConstants.java, src/main/java/frc/constants/DriveConstants.java, src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/commands/DriveToChargeStation.java, src/main/java/frc/robot/commands/DriveToDistance.java, src/main/java/frc/robot/commands/DriveToDistancePID.java, src/main/java/frc/robot/subsystems/Arm.java, src/main/java/frc/robot/subsystems/DriveSubsystem.java
Changes to position encoder factors for spark max to output usable encoder positions.
=> Changes to Position encoder factors

build.gradle, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/subsystems/SignalLEDs.java
- Hide implementation of 0, 1, or 2 physical LED strings
- Update interface for setting active or default pattern
- Implement sample `CommandXboxController` to replace `XboxController` (commented in `RobotContainer.java`)
- Depends on WPILib v2023.2.1
=> Enhance LED string functionality

src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/subsystems/SignalLEDs.java
Add Colonels and Countdown; periodic getAlliance
=> Led colonels

src/main/java/frc/robot/RobotContainer.java
Hope I didn't break anything too badly, but the new PID arm subsystem worked really well in testing with the Grover_2023 codebase and I wanted to merge it into the main robot code tree before I completely forget what I did today. Perhaps we need to breakout ConfigureButtons() into separate classes to facilitate testing of different subsystems without stepping all over each other? See you all Monday.
=> Replaced old Arm subsystem with ArmPIDSubystem

src/main/java/frc/robot/subsystems/DriveSubsystem.java
Using values from previous year for fwd and rot filtering.
Instead of DIY code use Filter library.
=> Add linear filter to teleop arcade drive

src/main/java/frc/constants/ClawConstants.java, src/main/java/frc/constants/GroundIntakeConstants.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/commands/AutoBalancePID.java, src/main/java/frc/robot/commands/DriveOnAndBalanceChargeStation.java, src/main/java/frc/robot/subsystems/ClawSubsystem.java, src/main/java/frc/robot/subsystems/GroundIntakeSubsystem.java
Remove dead code
Correct placement of constant for Claw
=> Cleanup after Wednesday commits

src/main/java/frc/constants/OIConstants.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/subsystems/ClawSubsystem.java, src/main/java/frc/robot/subsystems/GroundIntakeSubsystem.java
Create GamePiece mode: `CUBE` or `CONE`
Push GamePiece mode to the subsystems needing to know the mode: `Claw`, `GroundIntake`
TODO:
- Add ButtonBinding for switching mode in `RobotContainer`
- Add other subsystems needing mode: `LEDs`
- For subsystems `Claw`, `GroundIntake`
- Create state machines for tasks
- Implement subsystem methods
- Call methods from User Interface (`InstantCommand` or `SequentialCommandGroup`)
=> Start modal gamepiece

src/main/java/frc/constants/ArmConstants.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/subsystems/ArmProfiledPIDSubsystem.java, src/main/java/frc/robot/subsystems/TelescopePIDSubsystem.java
Limit manual rotation and telescope (needs testing)
Use constants instead of magic numbers
Start implementing OI from Robot Control specification document
=> Implement soft limits; use constants; start OI

src/main/java/frc/constants/ArmConstants.java, src/main/java/frc/constants/ClawConstants.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/subsystems/ArmProfiledPIDSubsystem.java, src/main/java/frc/robot/subsystems/ClawSubsystem.java
Set soft limits in spark max
Fixes to manual mode (deadzone, dampen joystick input)
Changed manual telescope to be right joystick y
Changed manual arm rotate to be left joystick y
Cube retrieve no longer turns rollers off after 1 second
=> Various changes to UI

src/main/java/frc/constants/ArmConstants.java, src/main/java/frc/constants/AutoConstants.java, src/main/java/frc/constants/ClawConstants.java, src/main/java/frc/constants/DriveConstants.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/commands/AutoBalancePID.java, src/main/java/frc/robot/commands/DriveToAprilTag.java, src/main/java/frc/robot/commands/DriveToChargeStation.java, src/main/java/frc/robot/commands/DriveToDistance.java, src/main/java/frc/robot/commands/basic/ClawRollerIn.java, src/main/java/frc/robot/commands/basic/ClawRollerOut.java, src/main/java/frc/robot/subsystems/ClawSubsystem.java, src/main/java/frc/robot/subsystems/DriveSubsystem.java
**Fixed**
- `ArmConstants`: separate Cone/Cube settings for angles and extensions
- Had to add a Temp section to get it to build. _Removal is high priority_
- Update Other constant files for clarity, remove magic numbers
- `AutoConstants`
- `ClawConstants`
- Refactor Auto Commands `Initialize`, `Execute`, `IsFinished` for clarity:
- `DriveToDistance`
- `DriveToChargeStation`
- `DriveToAprilTag`
**Todo**
- Refactor ArmConstants in Tab (Jeff?)
- Remove `ArmConstants` Temp section
- Deal with renamed `ArmConstants` in Subsystems (and Commands)
**Whew**
Then we can add more composite commands
=> Constants refactoring

src/main/java/frc/constants/AutoConstants.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/commands/AutoBalancePID.java, src/main/java/frc/robot/commands/Auto_RB_1.java, src/main/java/frc/robot/commands/Auto_RB_2.java, src/main/java/frc/robot/commands/Auto_RB_2_Exit_Balance.java, src/main/java/frc/robot/commands/Auto_RB_2_Pickup.java, src/main/java/frc/robot/commands/Auto_RB_3.java, src/main/java/frc/robot/commands/DriveOnAndBalanceChargeStation.java, src/main/java/frc/robot/commands/DriveToAprilTag.java, src/main/java/frc/robot/commands/DriveToChargeStation.java, src/main/java/frc/robot/commands/DriveToDistance.java, src/main/java/frc/robot/commands/TurnToAngle.java, src/main/java/frc/robot/commands/TurnToAngleProfiled.java
New commands per the spec
- `Auto_RB_1.java`
- `Auto_RB_2.java`
- `Auto_RB_2_Exit_Balance.java`
- `Auto_RB_2_Pickup.java`
- `Auto_RB_3.java `
=> Add new auto commands as from Saturday discussion

src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/commands/auto/RB_1.java, src/main/java/frc/robot/commands/auto/RB_1_Claw_Ready.java, src/main/java/frc/robot/commands/auto/RB_2_Exit_Balance.java, src/main/java/frc/robot/commands/auto/RB_2_Pickup.java, src/main/java/frc/robot/commands/driver/AutoArmScoreHigh.java
Fix accidental commits of merge lines
=> Fix errant git merge lines

src/main/java/frc/constants/AutoConstants.java, src/main/java/frc/robot/commands/SimpleBalance.java
Fix some minor errors; int and double consistency
=> SimpleBalance command corrections

src/main/java/frc/constants/AutoConstants.java, src/main/java/frc/robot/commands/DriveToChargeStation.java, src/main/java/frc/robot/commands/auto/RB_1.java, src/main/java/frc/robot/commands/auto/RB_1_Claw_Ready.java, src/main/java/frc/robot/commands/auto/RB_2.java, src/main/java/frc/robot/commands/auto/RB_3.java, src/main/java/frc/robot/commands/auto/RB_3_Claw_Ready.java
Also set initialPitch to 0 in DriveToChargeStation command
=> Tweak Simple Balance constants; Autobalance kP

src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/commands/DriveToDistanceVision.java, src/main/java/frc/robot/commands/DriveTowardsPose.java, src/main/java/frc/robot/commands/auto/RB_2_Arm_Pickup.java, src/main/java/frc/robot/commands/auto/RB_2_Exit_Balance_Vision.java
Re-fix function signature for `DriveToDistanceVision`
_Note: Merge to master before creating PRs makes life easier_
=> Fix incorrect merges around function signatures

src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/commands/auto/RB_2_Exit_Turn_Balance_Vision.java
=> Binded a few buttons to auto tests

src/main/deploy/pathplanner/Blue 1 McDouble Deluxe.path, src/main/java/frc/board/AutonomousTab.java, src/main/java/frc/robot/Paths.java, src/main/java/frc/robot/commands/auto/Blue_1_McDouble_Deluxe.java, src/main/java/frc/robot/subsystems/DriveSubsystem.java
If we have spare time on the practice field we should try this, I think we may be able to get it working with a tiny bit of tuning.
=> Substation McDouble Deluxe
